#! /bin/bash

#while true 
#  do 
#      xsetroot -name "$(date)"
#      sleep 1
#  done &

#Now I'm using dwmblocks for status bar
dwmblocks &
# Note here & is important other process won't end because of loop
nitrogen --restore &
xfce4-power-manager &
#/usr/lib/pentablet/pentablet.sh &
exec dwm

